[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/billing/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/items/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/accounting/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reports/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "/index.html"
  status = 200
  force = true
